# Development environment

version: '3.7'
services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
